language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
services:
  - mongodb
before_script:
  - sleep 15
script:
  - npm install
  - npm test
after_success:
  - npm run coverage
